### ISSUE TITLE
Error when starting the containers

### ISSUE THREAD

**Issue by Rainson12** [harness/harness-cd-community#41]
Dear harness Team,
when starting the containers using `docker-compose up` without the -d so that I am able to see the response, one of the containers will fail to start:
```
PS C:\tmp\harness-cd-community\docker-compose\harness> docker-compose up
Creating network "harness_harness-network" with the default driver
Creating volume "harness_mongo_data" with default driver
Creating harness_mongo_1 ...
Creating harness_delegate-proxy_1   ... done
Creating harness_redis_1            ... done
Creating harness_mongo_1            ... done
Creating harness_platform-service_1 ...
Creating harness_pipeline-service_1 ... done
Creating harness_manager_1          ...
Creating harness_platform-service_1 ... done
Creating harness_ng-ui_1            ...
Creating harness_manager_1          ... done
Creating harness_ng-manager_1       ... done
Creating harness_log-service_1      ... done
Creating harness_scm_1              ... done
Creating harness_ng-ui_1            ... done
Creating harness_proxy_1            ... done

ERROR: for ng-auth-ui  Cannot start service ng-auth-ui: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: unable to set memory limit to 12582912 (current usage: 14794752, peak usage: 15089664): unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by sean-harness** [comment]
Hi @Rainson12, thank you for filing an issue. Looking at the error message the app seems to be crashing due to the memory limit being too low. There is instructions in the readme which will help you to increase your Docker Desktop memory allocation, please see step 1 under [Start Harness CD](https://github.com/harness/harness-cd-community/tree/main/docker-compose/harness#start-harness-cd).

You can the below command to view how much memory is currently available to docker, look for the `Total Memory` field.
```
docker system info
```

**Comment by mrsantons** [comment]
Hello @Rainson12 👋🏻  , I am happy to provide any help you need, please let me know and we can set up a zoom to get you setup! You can ping me in our [Community Slack](https://join.slack.com/t/harnesscommunity/shared_invite/zt-y4hdqh7p-RVuEQyIl5Hcx4Ck8VCvzBw) @ Marie Antons and you can join the #cd-community channel as well!

**Comment by Rainson12** [comment]
fixed it updating the wsl config setting the max memory consumption to 24gig

**Comment by mrsantons** [comment]
Awesome! Happy you got it sorted @Rainson12! Let me know if I can assist in any other way!
