### ISSUE TITLE
Harness fails to run with docker-compose

### ISSUE THREAD

**Issue by ezzaze** [harness/harness-cd-community#58]
Hello everyone, 
Im having issues with harness setup using docker-compose, I have already ran  `docker-compose up -d` and everything went smoothly, but when I checked with `docker ps`, the container is stuck at restarting 
`
CONTAINER ID   IMAGE                             COMMAND                  CREATED         STATUS         
0837218ad128   harness/ng-manager-signed:77116   "./run.sh"               8 minutes ago   Restarting (1) 41 seconds ago       
`

When I checked the logs, this was the output :
`
docker logs 0837218ad128
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error
exec ./run.sh: exec format error

`
Any idea what could be the reason?

**Comment by ezzaze** [comment]
This is the docker info output

Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 6
  Running: 1
  Paused: 0
  Stopped: 5
 Images: 14
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-1021-oracle
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 23.43GiB
 Name: instance-20221210-2330
 ID: STBP:JL5L:RDZ4:AFRA:MFET:IFK6:JLPE:VBHX:ZS4N:JTKU:LERT:S7MA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by Ompragash** [comment]
hey @ezzaze, are you still facing this issue?

What is the OS you're trying to set this up on?

**Comment by ezzaze** [comment]
@Ompragash , apparently I tried to run it on an arm64 instead of amd64. Because once I tried on another amd64 the container started without any issues, hopefully sometime soon we get the support for the other arch

**Comment by Ompragash** [comment]
@ezzaze I am Glad, you got it working, and for the `arm64` feel free to file an RFE and we can see how & when it can be implemented or also the possibilities and update the RFE accordingly:)

Closing this one out for now!
