### ISSUE TITLE
Unable to start the service/environment

### ISSUE THREAD

**Issue by PirATesofArabian** [harness/harness-cd-community#71]
**Describe the bug**
I'm trying to bring up the harness cd manager ,but it's getting timedout
tried with timeout seconds from 180-500s , it timesout all the time

**To Reproduce**
1. Follow same steps to bring up the environment till 4 (both docker-compose and helm way)
2. docker-compose run --rm proxy wait-for-it.sh ng-manager:7090 -t 180 (running this will timeout)

**Expected behavior**
It will run properly and be able to open up the envirnoment in localhost in next step

**Screenshots**
➜  harness git:(main) docker-compose run --rm proxy wait-for-it.sh ng-manager:7090 -t 180
[+] Running 5/5
 ⠿ Container harness-platform-service-1  Running                                                                                                                             0.0s
 ⠿ Container harness-delegate-proxy-1    Running                                                                                                                             0.0s
 ⠿ Container harness-ng-ui-1             Running                                                                                                                             0.0s
 ⠿ Container harness-pipeline-service-1  Running                                                                                                                             0.0s
 ⠿ Container harness-manager-1           Recreated                                                                                                                          10.7s
[+] Running 1/1
 ⠿ Container harness-manager-1  Started                                                                                                                                      0.7s
wait-for-it.sh: waiting 180 seconds for ng-manager:7090
/bin/wait-for-it.sh: line 62:    16 Killed                  timeout $WAITFORIT_BUSYTIMEFLAG $WAITFORIT_TIMEOUT $0 --child --host=$WAITFORIT_HOST --port=$WAITFORIT_PORT --timeout=$WAITFORIT_TIMEOUT
wait-for-it.sh: timeout occurred after waiting 180 seconds for ng-manager:7090
➜  harness git:(main) docker-compose run --rm proxy wait-for-it.sh ng-manager:7090 -t 500
[+] Running 5/0
 ⠿ Container harness-delegate-proxy-1    Running                                                                                                                             0.0s
 ⠿ Container harness-ng-ui-1             Running                                                                                                                             0.0s
 ⠿ Container harness-platform-service-1  Running                                                                                                                             0.0s
 ⠿ Container harness-pipeline-service-1  Running                                                                                                                             0.0s
 ⠿ Container harness-manager-1           Running                                                                                                                             0.0s
wait-for-it.sh: waiting 500 seconds for ng-manager:7090
/bin/wait-for-it.sh: line 62:    17 Killed                  timeout $WAITFORIT_BUSYTIMEFLAG $WAITFORIT_TIMEOUT $0 --child --host=$WAITFORIT_HOST --port=$WAITFORIT_PORT --timeout=$WAITFORIT_TIMEOUT
wait-for-it.sh: timeout occurred after waiting 500 seconds for ng-manager:7090
➜  harness git:(main)

**Installation Method**
- [ ] Docker Compose
- [ ] Helm

**Environment (please complete the following information):**
 - OS: MacOS ventura 13.2.1

**Comment by harnesspravin** [comment]
Hi @PirATesofArabian ,

# For Docker compose :

1] After executing the command: $ docker-compose up -d
2] Wait for some time to check if all the processes are up and in the running state (Healthy State)

$ docker-compose ps

Once all the pods are healthy then, execute  Below : 
$ docker-compose run --rm proxy wait-for-it.sh ng-manager:7090 -t 180

Depending upon VM resources and CPU speed,  pods may take more time to become healthy.



# For Helm : 

After executing 
$ helm install harness ./harness --create-namespace --namespace harness 

Wait for all the pods to be UP and Running, and Monitor Columns READY and STATUS. 
In the READY column, all pods should show 1/1 and STATUS Running

You can use the below command to monitor the pod status :  

$ watch -n 1 kubectl get pods -n harness  

If everything UP and  running,  then execute : 

$ kubectl wait --namespace harness --timeout 900s --selector app=proxy --for condition=Ready pods.

**Comment by PirATesofArabian** [comment]
Hello pravin,
Thanks for looking into it 
I finally found the issue.
I am running M1 Mac with amd64 so it wasn't working,tried on normal Ubuntu and it worked
