### ISSUE TITLE
Harness Delegate Error

### ISSUE THREAD

**Issue by robertowu16** [harness/harness-cd-community#85]
Hi!
I recently try to self host Harness CD, but I always got error when I try to run harness delegate on my k8s. 

1. Download k8s manifest from account settings -> account resources -> delegate -> new delegate
2. Apply the manifest on k8s.
3. See error

![image](https://github.com/harness/harness-cd-community/assets/38288312/59fb073c-1f39-44a0-8237-1070813a88d7)
 I already try on Windows 10 & Linux for host Harness CD

Anyone face the same issue there? What should I do to solve this? Thanks.

**Comment by ravilach** [comment]
Repo is deprecated. Will close.
